packages:
  - packages/*

onlyBuiltDependencies:
  - '@prisma/client'
  - '@prisma/engines'
  - '@swc/core'
  - '@tailwindcss/oxide'
  - '@temporalio/core-bridge'
  - esbuild
  - prisma
  - protobufjs
